name: Lite Server Deploy

on:
  push:
    branches:
      - main
    paths:
      - "lite-server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lite-server

    env:
      IMAGE_NAME: crpi-ixqtkyv5jyilbxg5.cn-guangzhou.personal.cr.aliyuncs.com/kevinlau/blog-lite-server:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create .env file from GitHub Secrets
        run: |
          echo "PORT=3001" > .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWD=${{ secrets.DB_PASSWD }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME .
          docker image prune -f

      - name: Login to Aliyun
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin crpi-ixqtkyv5jyilbxg5.cn-guangzhou.personal.cr.aliyuncs.com

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      IMAGE_NAME: crpi-ixqtkyv5jyilbxg5.cn-guangzhou.personal.cr.aliyuncs.com/kevinlau/blog-lite-server:latest

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE_NAME="crpi-ixqtkyv5jyilbxg5.cn-guangzhou.personal.cr.aliyuncs.com/kevinlau/blog-lite-server:latest"
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin crpi-ixqtkyv5jyilbxg5.cn-guangzhou.personal.cr.aliyuncs.com
            docker pull $IMAGE_NAME
            docker rm -f blog-lite-server 2>/dev/null || echo "Container blog-lite-server removed or does not exist"
            docker run -d --name blog-lite-server -v /www/wwwroot/lite-server.kevinlau.cn/.env:/app/.env -p 20239:3001 $IMAGE_NAME
