name: Server Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    env:
      IMAGE_NAME: crpi-ixqtkyv5jyilbxg5.cn-guangzhou.personal.cr.aliyuncs.com/kevinlau/blog-server:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create .env.prod file from GitHub Secrets
        run: |
          echo "NODE_ENV=production" >> .env
          echo "DB_HOST=${{ secrets.SERVER_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWD=${{ secrets.DB_PASSWD }}" >> .env
          echo "DB_DATABASE=blog" >> .env

      - name: Build Docker Image
        run: |
          # 构建多架构镜像以提高兼容性
          docker build -t $IMAGE_NAME .
          # 压缩镜像层以减少推送时间
          docker image prune -f

      - name: Login to Aliyun
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin crpi-ixqtkyv5jyilbxg5.cn-guangzhou.personal.cr.aliyuncs.com

      - name: Push Docker Image with retry
        run: |
          docker push $IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      IMAGE_NAME: crpi-ixqtkyv5jyilbxg5.cn-guangzhou.personal.cr.aliyuncs.com/kevinlau/blog-server:latest

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} crpi-ixqtkyv5jyilbxg5.cn-guangzhou.personal.cr.aliyuncs.com
            docker pull $IMAGE_NAME
            docker ps -q --filter "name=blog-server" | grep -q . && docker stop blog-server || echo "Container blog-server is not running"
            docker ps -a -q --filter "name=blog-server" | grep -q . && docker rm blog-server || echo "Container blog-server does not exist"
            docker run -d --name blog-server -p 3000:20238 $IMAGE_NAME
